Repository Mostly-BS-Totally-BA/mostly-bs-totally-ba, pull requests merged in 2018-04, with the labels that each got.

#102 Hud stuff
  .DS_Store
  CSE442_Project/.DS_Store
  CSE442_Project/.vs/CSE442_Project/xs/UserPrefs.xml
  CSE442_Project/Assets/.DS_Store
  CSE442_Project/Assets/Prefabs/Canvas/HUD.prefab
  CSE442_Project/Assets/Prefabs/Canvas/NewLevel.prefab
  CSE442_Project/Assets/Prefabs/Canvas/PauseMenu.prefab
  CSE442_Project/Assets/Prefabs/Canvas/PauseMenu.prefab.meta
  CSE442_Project/Assets/Prefabs/Canvas/StatBoost.prefab
  CSE442_Project/Assets/Prefabs/Canvas/StatBoost.prefab.meta
  CSE442_Project/Assets/Scripts/Player Scripts/Player_Movement.cs
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/Scripts/_Game/UIManager.cs
  CSE442_Project/Assets/_Scenes/LVL1_to_LVL2_Transition.unity
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MAP_Level2.unity
  CSE442_Project/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#121 Puzzle Updated
  CSE442_Project/Assets/Prefabs/Potions/Potion.prefab
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MAP_Level2.unity
Labels: beta release

#122 Added new instructions and fixed camera size
  CSE442_Project/.DS_Store
  CSE442_Project/Assets/.DS_Store
  CSE442_Project/Assets/Prefabs/Canvas/PauseMenu.prefab
  CSE442_Project/Assets/Prefabs/Objects.meta
  CSE442_Project/Assets/Sprites/.DS_Store
  CSE442_Project/Assets/Sprites/GUI/C2.png
  CSE442_Project/Assets/Sprites/GUI/C2.png.meta
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MENU_Main.unity
  CSE442_Project/CSE442_Project.csproj
  CSE442_Project/ProjectSettings/GraphicsSettings.asset
Labels: beta release, enhancement

#130 Correct link
  README.md
Labels: beta release

#150 Collaboration
  CSE442_Project/.DS_Store
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/_Scenes/MENU_Main.unity
  CSE442_Project/ProjectSettings/ProjectVersion.txt
Labels: Feature Request, enhancement

#160 Minimaps
  CSE442_Project/Assets/Prefabs/minimap.meta
  CSE442_Project/Assets/Prefabs/minimap/minimap_texture.renderTexture
  CSE442_Project/Assets/Prefabs/minimap/minimap_texture.renderTexture.meta
  CSE442_Project/Assets/Scripts/Interaction/From_lvl1_to_Transition.cs
  CSE442_Project/Assets/Scripts/Interaction/From_lvl1_to_Transition.cs.meta
  CSE442_Project/Assets/Scripts/Interaction/Treasure_pickup.cs
  CSE442_Project/Assets/Scripts/MinimapMovement.cs
  CSE442_Project/Assets/Scripts/MinimapMovement.cs.meta
  CSE442_Project/Assets/Sprites/Objects/Decor0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Decor1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Door0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Door1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Effect0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Effect1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Fence.png.meta
  CSE442_Project/Assets/Sprites/Objects/Floor.png.meta
  CSE442_Project/Assets/Sprites/Objects/Ground0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Ground1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Hill0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Hill1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Map0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Map1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Ore0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Ore1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Pit0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Pit1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Tile.png.meta
  CSE442_Project/Assets/Sprites/Objects/Trap0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Trap1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Tree0.png.meta
  CSE442_Project/Assets/Sprites/Objects/Tree1.png.meta
  CSE442_Project/Assets/Sprites/Objects/Wall.png.meta
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MAP_Level2.unity
  CSE442_Project/Assets/_Scenes/MAP_preFinalLevel.unity
  CSE442_Project/Assets/_Scenes/MENU_Main.unity
  CSE442_Project/CSE442_Project.csproj
  CSE442_Project/ProjectSettings/EditorSettings.asset
  CSE442_Project/ProjectSettings/GraphicsSettings.asset
Labels: official release

#161 Save load wipe
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/Scripts/_Game/Save.cs
  CSE442_Project/Assets/Scripts/_Game/SaveLoad.cs
Labels: official release

#145 Add the zombies spawning
  CSE442_Project/Assets/Scripts/Enemies/LVL2/LVL2Boss.cs
Labels: Feature Request, enhancement

#162 Arrow key functionality
  CSE442_Project/ProjectSettings/InputManager.asset
  CSE442_Project/ProjectSettings/ProjectVersion.txt
Labels: Feature Request

#166 hotfix changes
  CSE442_Project/Assets/Scripts/Enemies/LVL2/Necromancer.cs
  CSE442_Project/Assets/_Scenes/MAP_Level2.unity
  CSE442_Project/CSE442_Project.csproj
Labels: bug
