Repository Mostly-BS-Totally-BA/mostly-bs-totally-ba, pull requests merged in 2018-03, with the labels that each got.

#59 Ui hud
  CSE442_Project/.vs/CSE442_Project/xs/UserPrefs.xml
  CSE442_Project/Assets/.DS_Store
  CSE442_Project/Assets/Scripts/Enemy_movement.cs
  CSE442_Project/Assets/Scripts/MainMenu.cs
  CSE442_Project/Assets/Scripts/Player Scripts/Player_Movement.cs
  CSE442_Project/Assets/Scripts/Player Scripts/Player_Movement.cs.meta
  CSE442_Project/Assets/Scripts/Player_Movement.cs
  CSE442_Project/Assets/Scripts/_Game.meta
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs.meta
  CSE442_Project/Assets/Scripts/_Game/LoadScene.cs
  CSE442_Project/Assets/Scripts/_Game/LoadScene.cs.meta
  CSE442_Project/Assets/Scripts/_Game/MainMenu.cs
  CSE442_Project/Assets/Scripts/_Game/MainMenu.cs.meta
  CSE442_Project/Assets/Scripts/_Game/PauseMenu.cs
  CSE442_Project/Assets/Scripts/_Game/PauseMenu.cs.meta
  CSE442_Project/Assets/Scripts/_Game/Properties.cs
  CSE442_Project/Assets/Scripts/_Game/Properties.cs.meta
  CSE442_Project/Assets/Scripts/_Game/Singleton.cs
  CSE442_Project/Assets/Scripts/_Game/Singleton.cs.meta
  CSE442_Project/Assets/Scripts/_Game/UIManager.cs
  CSE442_Project/Assets/Scripts/_Game/UIManager.cs.meta
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MENU_Main.unity
  CSE442_Project/CSE442_Project.csproj
Labels: alpha release, enhancement

#64 Bug Fix - lvl 1 Puzzle
  CSE442_Project/Assets/Scripts/Interaction/lvl1_Puzzle_Interactions.cs
Labels: alpha release, bug

#61 Enemy attack 2 electric boogaloo
  CSE442_Project/Assets/Animations/Animations/LVL1Boss.meta
  CSE442_Project/Assets/Animations/Animations/LVL1Boss/LVL1Boss.controller
  CSE442_Project/Assets/Animations/Animations/LVL1Boss/LVL1Boss.controller.meta
  CSE442_Project/Assets/Animations/Animations/LVL1Boss/Lvl1Boss.anim
  CSE442_Project/Assets/Animations/Animations/LVL1Boss/Lvl1Boss.anim.meta
  CSE442_Project/Assets/Animations/Animations/player animations/player_down.anim
  CSE442_Project/Assets/Animations/Animations/player animations/player_left.anim
  CSE442_Project/Assets/Animations/Animations/player animations/player_right.anim
  CSE442_Project/Assets/Prefabs/Enemies/LVL1Boss.prefab
  CSE442_Project/Assets/Prefabs/Enemies/LVL1Boss.prefab.meta
  CSE442_Project/Assets/Prefabs/Player/PlayerSprite.prefab
  CSE442_Project/Assets/Scripts/CameraMovement.cs
  CSE442_Project/Assets/Scripts/Enemies.meta
  CSE442_Project/Assets/Scripts/Enemies/Enemy_movement.cs
  CSE442_Project/Assets/Scripts/Enemies/Enemy_movement.cs.meta
  CSE442_Project/Assets/Scripts/Enemies/LVL1Boss.cs
  CSE442_Project/Assets/Scripts/Enemies/LVL1Boss.cs.meta
  CSE442_Project/Assets/Scripts/Player Scripts/PlayerAttack.cs
  CSE442_Project/Assets/Scripts/Player Scripts/Player_Movement.cs
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/CSE442_Project.csproj
Labels: alpha release, enhancement

#73 Added comments, fixed gameover bug, fixed player health/no death issue
  CSE442_Project/.vs/CSE442_Project/xs/UserPrefs.xml
  CSE442_Project/Assets/Prefabs/Objects.meta
  CSE442_Project/Assets/Scripts/Player Scripts/Player_Movement.cs
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/Scripts/_Game/LoadScene.cs
  CSE442_Project/Assets/Scripts/_Game/MainMenu.cs
  CSE442_Project/Assets/Scripts/_Game/PauseMenu.cs
  CSE442_Project/Assets/Scripts/_Game/UIManager.cs
  CSE442_Project/Assets/_Scenes/MAP_Level2.unity
  CSE442_Project/CSE442_Project.csproj
  CSE442_Project/ProjectSettings/GraphicsSettings.asset
Labels: alpha release, bug

#75 Enemy placements v2
  CSE442_Project/Assets/Prefabs/Enemies/LVL2/LVL2Boss.prefab
  CSE442_Project/Assets/Prefabs/Enemies/LVL2/Necromancer.prefab
  CSE442_Project/Assets/Prefabs/Enemies/LVL2/RasiedZombie.prefab
Labels: alpha release

#99 Simple save/load added
  .DS_Store
  CSE442_Project/.DS_Store
  CSE442_Project/.vs/CSE442_Project/xs/UserPrefs.xml
  CSE442_Project/Assets/Prefabs/Canvas/HUD.prefab
  CSE442_Project/Assets/Prefabs/Canvas/NewLevel.prefab
  CSE442_Project/Assets/Prefabs/Canvas/PauseMenu.prefab
  CSE442_Project/Assets/Scripts/Enemies/Enemy_movement.cs
  CSE442_Project/Assets/Scripts/Enemies/LVL1Boss.cs
  CSE442_Project/Assets/Scripts/_Game/GameManager.cs
  CSE442_Project/Assets/Scripts/_Game/MainMenu.cs
  CSE442_Project/Assets/Scripts/_Game/PauseMenu.cs
  CSE442_Project/Assets/Scripts/_Game/Save.cs
  CSE442_Project/Assets/Scripts/_Game/Save.cs.meta
  CSE442_Project/Assets/Scripts/_Game/SaveLoad.cs
  CSE442_Project/Assets/Scripts/_Game/SaveLoad.cs.meta
  CSE442_Project/Assets/Scripts/_Game/UIManager.cs
  CSE442_Project/Assets/_Scenes/MAP_Level1.unity
  CSE442_Project/Assets/_Scenes/MENU_Main.unity
  CSE442_Project/CSE442_Project.csproj
Labels: beta release, enhancement
